deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dest
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
    